apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
 name: fastapi-server

spec:
 scaleTargetRef:
   apiVersion: apps/v1
   kind: Deployment
   name: fastapi-server
 minReplicas: 1
 maxReplicas: 9
 targetCPUUtilizationPercentage: 80