apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: ${APP_ID}
  name: ${APP_ID}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${APP_ID}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: ${APP_ID}
    spec:
      containers:
      - image: gcr.io/${PROJECT_ID}/${IMAGE_ID}
        name: ${IMAGE_ID}
        ports:
        - containerPort: 80          
        resources: {}
status: {}
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
 name: ${APP_ID}-hpa

spec:
 scaleTargetRef:
   apiVersion: apps/v1
   kind: Deployment
   name: ${APP_ID}
 minReplicas: 1
 maxReplicas: 3
 targetCPUUtilizationPercentage: 80